package com.brainerd;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class testfile1 implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public testfile1() {
    }

}