package com.brainerd;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class testfile1 implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.math.BigDecimal field1;
   private java.math.BigInteger field2;
   private java.lang.Boolean field3;
   private java.lang.Character field4;
   private java.util.Date field5;

   private java.math.BigDecimal fld12;

   public testfile1()
   {
   }

   public java.math.BigDecimal getField1()
   {
      return this.field1;
   }

   public void setField1(java.math.BigDecimal field1)
   {
      this.field1 = field1;
   }

   public java.math.BigInteger getField2()
   {
      return this.field2;
   }

   public void setField2(java.math.BigInteger field2)
   {
      this.field2 = field2;
   }

   public java.lang.Boolean getField3()
   {
      return this.field3;
   }

   public void setField3(java.lang.Boolean field3)
   {
      this.field3 = field3;
   }

   public java.lang.Character getField4()
   {
      return this.field4;
   }

   public void setField4(java.lang.Character field4)
   {
      this.field4 = field4;
   }

   public java.util.Date getField5()
   {
      return this.field5;
   }

   public void setField5(java.util.Date field5)
   {
      this.field5 = field5;
   }

   public java.math.BigDecimal getFld12()
   {
      return this.fld12;
   }

   public void setFld12(java.math.BigDecimal fld12)
   {
      this.fld12 = fld12;
   }

   public testfile1(java.math.BigDecimal field1, java.math.BigInteger field2,
         java.lang.Boolean field3, java.lang.Character field4,
         java.util.Date field5, java.math.BigDecimal fld12)
   {
      this.field1 = field1;
      this.field2 = field2;
      this.field3 = field3;
      this.field4 = field4;
      this.field5 = field5;
      this.fld12 = fld12;
   }

}